session: 'root'
play: true
reset: false
debug: false
monitor: false
console: true
push_layers: false
push_sources: false
shuffle: false
shuffle_usepeak: true
shuffle_mode: 0
shuffle_switch_every: 16
shuffleable: ''
tempo: 120.00
beat: true
peak_bpm_detect: true
audio: 'off'
usestream: false
latency: -60
volume: 1.00
filter_type: 'off'
filter_frequency: 350
layer: 0
peak_threshold_end: 3.6